# Generated by Django 2.2.7 on 2020-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0001_initial_manualmigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcandidate',
            name='score_english',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='createcandidate',
            name='score_math',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='createcandidate',
            name='score_reasoning',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='score_english',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='score_math',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='score_reasoning',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
