# Generated by Django 2.2.7 on 2021-01-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0002_auto_20200123_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcandidate',
            name='testcomplete_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
