# Generated by Django 2.2.7 on 2019-12-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20191226_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option5',
            field=models.TextField(blank=True, default='0', null=True),
        ),
    ]
